"use client";

import { useEffect, useState } from "react";

type PredictionRow = {
  timestamp: string;
  zone: string;
  latitude: number;
  longitude: number;
  risk_score: number;
  severity_level: string;
  confidence: number;
  time_to_impact_hours: number | null;
  affected_area_km2: number;
  estimated_affected_population: number | null;
  risk_factors?: any;
  recommended_actions?: any;
};

type ApiResponse = {
  count: number;
  predictions: PredictionRow[];
};

export default function EnvironmentalPanel() {
  const [data, setData] = useState<ApiResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPredictions = async () => {
      try {
        const res = await fetch(
          "http://localhost:8000/api/v1/environmental/predictions?limit=5"
        );
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}`);
        }
        const json: ApiResponse = await res.json();
        setData(json);
      } catch (err: any) {
        setError(err.message || "Failed to load predictions");
      } finally {
        setLoading(false);
      }
    };

    fetchPredictions();
    // Optional: auto-refresh every 60 seconds
    const timer = setInterval(fetchPredictions, 60000);
    return () => clearInterval(timer);
  }, []);

  if (loading) {
    return <p className="text-sm text-slate-600">Loading environmental predictions...</p>;
  }

  if (error) {
    return <p className="text-sm text-red-600">Error: {error}</p>;
  }

  if (!data || data.count === 0) {
    return <p className="text-sm text-slate-600">No predictions available.</p>;
  }

  return (
    <div className="space-y-3">
      <div>
        <h2 className="text-xl font-semibold">
          Environmental Flood Risk (Last {data.count})
        </h2>
        <p className="text-xs text-slate-500 mt-1">
          Showing latest predictions generated by <b>agent_1_environmental</b>.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full text-xs border">
          <thead className="bg-slate-50">
            <tr>
              <th className="border px-2 py-1 text-left">Time</th>
              <th className="border px-2 py-1 text-left">Zone</th>
              <th className="border px-2 py-1 text-left">Risk</th>
              <th className="border px-2 py-1 text-left">Severity</th>
              <th className="border px-2 py-1 text-left">Confidence</th>
              <th className="border px-2 py-1 text-left">Time to impact (hrs)</th>
              <th className="border px-2 py-1 text-left">Affected area (km²)</th>
              <th className="border px-2 py-1 text-left">Est. population</th>
            </tr>
          </thead>
          <tbody>
            {data.predictions.map((p, idx) => (
              <tr key={idx} className="hover:bg-slate-50">
                <td className="border px-2 py-1">
                  {new Date(p.timestamp).toLocaleString()}
                </td>
                <td className="border px-2 py-1">{p.zone}</td>
                <td className="border px-2 py-1">
                  {(p.risk_score * 100).toFixed(1)}%
                </td>
                <td className="border px-2 py-1">{p.severity_level}</td>
                <td className="border px-2 py-1">
                  {(p.confidence * 100).toFixed(1)}%
                </td>
                <td className="border px-2 py-1">
                  {p.time_to_impact_hours ?? "-"}
                </td>
                <td className="border px-2 py-1">
                  {p.affected_area_km2.toFixed(2)}
                </td>
                <td className="border px-2 py-1">
                  {p.estimated_affected_population ?? "-"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
// frontend/app/dashboard/componentes/EnvironmentalPanel.tsx